orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0
version: 2.1
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: bookcafe-review-app_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: '%'
          MYSQL_USER: root
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

      # capistranoデプロイECSのコンテナデプロイに移行中
      # - add_ssh_keys:
      #     fingerprints:
      #       - "41:ce:db:36:2f:19:67:ff:6f:df:ee:ea:3d:5d:a3:f3"

      # - deploy:
      #     name: Capistrano deploy
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" != "master" ]; then
      #         exit 0
      #       fi
      #       bundle exec cap production deploy

workflows:
  # Nginxデプロイ
  nginx-build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
        account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
        aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
        aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
        create-repo: true
        dockerfile: ./docker/nginx/Dockerfile
        path: pathToMyDockerfile
        profile-name: myProfileName
        region: AWS_REGION_ENV_VAR_NAME
        repo: myECRRepository
        tag: 'latest,myECRRepoTag'
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

  # Railsデプロイ
  rails-build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
        account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
        aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
        aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
        create-repo: true
        dockerfile: ./docker/rails/Dockerfile
        path: pathToMyDockerfile
        profile-name: myProfileName
        region: AWS_REGION_ENV_VAR_NAME
        repo: myECRRepository
        tag: 'latest,myECRRepoTag'
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
